export const references = [
  {
    name: 'Higdon · Novice 5K',
    family: '5k',
    weeks: '8',
    runs: '3',
    long: '4.8 km',
    audience: 'Beginning runners; completion emphasis',
    url: 'https://www.halhigdon.com/training-programs/5k-training/novice-5k/',
  },
  {
    name: 'Higdon · Novice 10K',
    family: '10k',
    weeks: '8',
    runs: '3',
    long: '8.9 km',
    audience: 'Completion emphasis; lower-volume routine',
    url: 'https://www.halhigdon.com/training-programs/10k-training/novice-10k/',
  },
  {
    name: 'Pfitzinger · 10K',
    family: '10k',
    weeks: '12',
    runs: 'Varies',
    long: 'Higher-volume schedule',
    audience: 'Lowest family starts around 48 km/week; experienced runners',
    url: 'https://us.humankinetics.com/products/faster-road-racing',
  },
  {
    name: 'Higdon · Novice half',
    family: 'half',
    weeks: '12',
    runs: '3–4',
    long: '16.1 km',
    audience: 'Building toward a first half-marathon',
    url: 'https://www.halhigdon.com/training-programs/half-marathon-training/novice-1-half-marathon/',
  },
  {
    name: 'Hansons · Advanced marathon',
    family: 'marathon',
    weeks: '18',
    runs: '6',
    long: '25.75 km (16 mi)',
    audience:
      'Classic advanced schedule; cumulative fatigue and marathon-pace work. Not a universal long-run cap.',
    url: 'https://hansons-running.com/pages/training-plans',
  },
  {
    name: 'Pfitzinger · Advanced Marathoning',
    family: 'marathon',
    weeks: '12 / 18',
    runs: 'Varies by volume',
    long: 'Varies by schedule',
    audience:
      'Established mileage; medium-long running, threshold, marathon specificity and recovery.',
    url: 'https://us.humankinetics.com/products/advanced-marathoning-4th-edition',
  },
  {
    name: 'Higdon · Novice marathon',
    family: 'marathon',
    weeks: '18',
    runs: '4',
    long: '32.2 km',
    audience: 'Existing running base; completion emphasis',
    url: 'https://www.halhigdon.com/training-programs/marathon-training/novice-1-marathon/',
  },
  {
    name: 'Higdon · 50K ultra',
    family: 'ultra',
    weeks: '26',
    runs: '5',
    long: '4–5 hours',
    audience: 'Established runners; time on feet and walking practice',
    url: 'https://www.halhigdon.com/training-programs/more-training/ultramarathon-50k/',
  },
];
