import type { WorkoutTemplate } from './workout-library';

/** Original doses and wording. Book references: Advanced Marathoning 3e,
 * chapter 8 (session purposes), chapters 9–12 (phase emphasis).
 */
const tempo = (minutes: number): WorkoutTemplate => ({
  id: `marathon-book-lt-${minutes}`,
  title:
    minutes < 20 ? 'Introductory continuous tempo' : 'Continuous threshold run',
  kind: 'tempo',
  stimulus: 'threshold',
  goals: ['marathon'],
  phases: ['Foundation', 'Build', 'Race preparation', 'Taper', 'Race week'],
  purpose:
    minutes < 20
      ? 'A shorter introduction to continuous tempo, scaled to your current workout background. Build comfort before extending the sustained effort.'
      : 'Sustain a controlled, even tempo at your current roughly one-hour race effort. This develops the aerobic strength needed to hold marathon pace.',
  cue: 'Current one-hour race effort · comfortably hard · 6 / 10 · no sprint finish',
  workSeconds: [minutes * 60],
  recoverySeconds: 0,
  minimumReps: 1,
  maximumReps: 1,
  intensity: 6,
  continuousStepSeconds: minutes < 20 ? 180 : 300,
  minimumContinuousSeconds: minutes < 20 ? 360 : 1200,
  warmupSeconds: minutes < 12 ? 600 : 900,
  cooldownSeconds: minutes < 12 ? 300 : 600,
});
const marathon = (minutes: number): WorkoutTemplate => ({
  id: `marathon-book-mp-${minutes}`,
  title: 'Long run with sustained marathon pace',
  kind: 'long',
  stimulus: 'race-rhythm',
  goals: ['marathon'],
  phases: ['Foundation', 'Build', 'Race preparation'],
  purpose:
    'Run the opening distance easily, then settle into sustained, realistic marathon effort. Practise familiar fuel and kit. This uses one of the week’s workout slots.',
  cue: 'Controlled marathon effort · 4–5 / 10 · ease back if it stops feeling sustainable',
  workSeconds: [minutes * 60],
  recoverySeconds: 0,
  minimumReps: 1,
  maximumReps: 1,
  intensity: 5,
  warmupSeconds: 900,
  cooldownSeconds: 300,
  maxWorkFraction: 0.6,
  continuousStepSeconds: 300,
  minimumContinuousSeconds: 1200,
});

/** Distinct main sets for runners who already do regular workouts. Distances
 * require a saved pace target; timed counterparts never invent a race pace. */
function structured(
  family: string,
  stimulus: 'threshold' | 'aerobic-power' | 'race-rhythm',
  seconds: number[],
  metres: number[],
  minimum: number,
  maximum: number,
  purpose: string,
  extra: Partial<WorkoutTemplate> = {},
): WorkoutTemplate[] {
  const base: WorkoutTemplate = {
    id: '',
    title: family,
    goals: ['marathon'],
    phases: ['Foundation', 'Build', 'Race preparation', 'Taper'],
    kind: stimulus === 'aerobic-power' ? 'intervals' : 'tempo',
    stimulus,
    purpose,
    cue:
      stimulus === 'aerobic-power'
        ? 'Current 5K effort · quick and controlled · 7 / 10 · never sprint'
        : stimulus === 'threshold'
          ? 'Current one-hour race effort · comfortably hard · 6 / 10'
          : 'Controlled marathon effort · 4–5 / 10 · patient and sustainable',
    intensity:
      stimulus === 'aerobic-power' ? 7 : stimulus === 'threshold' ? 6 : 5,
    workSeconds: seconds,
    recoverySeconds: 120,
    recoveryMovement: 'run',
    minimumReps: minimum,
    maximumReps: maximum,
    warmupSeconds: 600,
    cooldownSeconds: 300,
    ...extra,
  };
  return [
    { ...base, id: `marathon-book-${family}-timed` },
    { ...base, id: `marathon-book-${family}-metres`, workMetres: metres },
  ];
}

export const MARATHON_WORKOUTS: WorkoutTemplate[] = [
  ...structured(
    'tempo-blocks',
    'threshold',
    [600],
    [2000],
    2,
    3,
    'Build sustained threshold endurance in long, even blocks. Jog for two minutes between blocks; finish in control.',
  ),
  ...structured(
    'tempo-repeats',
    'threshold',
    [300],
    [1000],
    3,
    6,
    'Accumulate threshold running in repeatable blocks. Keep the opening and final repetitions at the same comfortably hard effort.',
    { recoverySeconds: 90 },
  ),
  ...structured(
    'tempo-cut-down',
    'threshold',
    [600, 480, 360],
    [3000, 2000, 1000],
    3,
    3,
    'Run the longest tempo block first, then two shorter blocks at the same effort. The shorter finish changes the rhythm without turning into a sprint.',
  ),
  ...structured(
    'on-off',
    'threshold',
    [300],
    [1000],
    3,
    6,
    'Alternate tempo with genuinely easy floats. Keep every off block conversational; this develops pace control without racing the recoveries.',
    { recoverySeconds: 0, floatSeconds: 120 },
  ),
  ...structured(
    'six-hundred',
    'aerobic-power',
    [180],
    [600],
    4,
    8,
    'Build aerobic power with controlled longer repetitions and a 90-second easy jog. Keep the last repeat as smooth as the first.',
    { recoverySeconds: 90 },
  ),
  ...structured(
    'split-repeats',
    'aerobic-power',
    [90],
    [400],
    6,
    12,
    'Run two equal sets of controlled repetitions. Jog between repeats and take one additional minute between sets.',
    { recoverySeconds: 60, setCount: 2, setRecoverySeconds: 60 },
  ),
  ...structured(
    'pyramid',
    'aerobic-power',
    [120, 180, 240, 180, 120],
    [400, 600, 800, 600, 400],
    5,
    5,
    'Climb and descend a five-step pyramid. Hold the same controlled effort as the repetitions lengthen and shorten; jog 90 seconds between each.',
    { recoverySeconds: 90 },
  ),
  ...structured(
    'long-into-short',
    'aerobic-power',
    [180, 180, 180, 180, 60, 60, 60, 60],
    [600, 600, 600, 600, 200, 200, 200, 200],
    8,
    8,
    'Run four longer repetitions, then four shorter ones. Use the short finish to practise quick, relaxed form at the same effort, never maximal speed.',
    { recoverySeconds: 90 },
  ),
  ...structured(
    'marathon-blocks',
    'race-rhythm',
    [720],
    [2000],
    2,
    3,
    'Rehearse sustainable marathon effort in substantial blocks, with easy jogging between. This replaces the interval session and counts toward the weekly workout limit.',
  ),
  {
    id: 'marathon-book-secondary-steady',
    title: 'Marathon effort blocks',
    kind: 'tempo',
    stimulus: 'race-rhythm',
    goals: ['marathon'],
    phases: ['Foundation', 'Build', 'Race preparation'],
    purpose:
      'Practise controlled marathon effort inside an easy run. This optional second workout fits within your existing week; a marathon-effort long run takes its place.',
    cue: 'Patient marathon effort · 4–5 / 10 · keep something in reserve',
    workSeconds: [480],
    recoverySeconds: 180,
    minimumReps: 1,
    maximumReps: 3,
    intensity: 5,
    warmupSeconds: 600,
    cooldownSeconds: 300,
  },
  {
    id: 'marathon-book-steady-intro',
    title: 'Short steady introduction',
    kind: 'tempo',
    stimulus: 'threshold',
    goals: ['marathon'],
    phases: ['Foundation', 'Build', 'Race preparation'],
    purpose:
      'Practise one short, controlled steady effort within an easy run. This is an introduction to sustained running, not a full threshold workout. Finish with something in reserve.',
    cue: 'Steady and comfortable · 5–6 / 10 · keep the effort controlled',
    workSeconds: [360],
    recoverySeconds: 0,
    minimumReps: 1,
    maximumReps: 1,
    intensity: 5,
    warmupSeconds: 600,
    cooldownSeconds: 300,
  },
  {
    id: 'marathon-book-strides',
    title: 'Easy run with relaxed strides',
    kind: 'easy',
    stimulus: 'economy',
    goals: ['marathon'],
    phases: ['Foundation', 'Build', 'Race preparation'],
    purpose:
      'Finish easy running with short, relaxed accelerations and full easy recoveries. Practise form without turning the day into an interval workout.',
    cue: 'Relaxed acceleration · quick feet · never strain or sprint',
    workSeconds: [20],
    recoverySeconds: 100,
    minimumReps: 4,
    maximumReps: 6,
    intensity: 6,
  },
  ...[6, 9, 12, 15, 20, 25, 30, 35, 40].map(tempo),
  ...Array.from({ length: 15 }, (_, i) => marathon(20 + i * 5)),
  ...[600, 800, 1000, 1200, 1600].map(
    (metres): WorkoutTemplate => ({
      id: `marathon-book-vo2-${metres}m`,
      title: `${metres} m repeats at current 5K pace`,
      kind: 'intervals',
      stimulus: 'aerobic-power',
      goals: ['marathon'],
      phases: ['Race preparation', 'Taper'],
      purpose:
        'A measured dose of current 5K-paced running late in marathon preparation. Keep repetitions even and jog the recoveries; endurance remains the priority.',
      cue: 'Current 5K effort · quick and controlled · 7 / 10 · never sprint',
      workSeconds: [180],
      workMetres: [metres],
      recoverySeconds: 120,
      recoveryRatio: 0.7,
      minimumReps: 3,
      maximumReps: 6,
      intensity: 7,
      warmupSeconds: 900,
      cooldownSeconds: 600,
    }),
  ),
  ...[180, 240, 300].map(
    (seconds): WorkoutTemplate => ({
      id: `marathon-book-vo2-${seconds}s`,
      title: 'Controlled 5K-effort repetitions',
      kind: 'intervals',
      stimulus: 'aerobic-power',
      goals: ['marathon'],
      phases: ['Race preparation', 'Taper'],
      purpose:
        'Controlled repetitions at current 5K effort, with generous easy jogging between. Time-based steps work without an estimated race pace.',
      cue: 'Current 5K effort · quick and controlled · 7 / 10 · never sprint',
      workSeconds: [seconds],
      recoverySeconds: Math.round(seconds * 0.7),
      minimumReps: 3,
      maximumReps: 6,
      intensity: 7,
      warmupSeconds: 900,
      cooldownSeconds: 600,
    }),
  ),
];
